export enum ErrorCodes {
    'RESOURCE_ALREADY_EXITS' = 'RESOURCE_ALREADY_EXITS',
    'USER_NOT_FOUND' = 'USER_NOT_FOUND',
    'INVALID_LOGIN_CREDENTIALS' = 'INVALID_LOGIN_CREDENTIALS',
    'INVALID_PASSWORD' = 'INVALID_PASSWORD',
    'INVALID_EMAIL' = 'INVALID_EMAIL',
    'INVALID_USER_TOKEN' = 'INVALID_USER_TOKEN',
    'INVALID_USER' = 'INVALID_USER',
    'PERMISSION_DENIED' = 'PERMISSION_DENIED',
    'INVALID_INPUT_FOR_ASSIGNING_PROJECTS' = 'INVALID_INPUT_FOR_ASSIGNING_PROJECTS',
}
